name: Build Android APK

on:
  push:
    branches: [ main ]  # 在推送到 main 分支时触发
  workflow_dispatch:    # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      
    - name: 设置 JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: 赋予 gradlew 执行权限
      run: chmod +x gradlew
      
    - name: 构建 APK
      run: ./gradlew assembleRelease  # 关键打包命令
      
    - name: 上传 APK 产物
      uses: actions/upload-artifact@v3
      with:
        name: app-release
        path: |
          */build/outputs/apk/**/*.apk
          */build/outputs/bundle/**/*.aab
